version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adoptapetnet

  backend:
    build: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - adoptapetnet

  frontend:
    build:
      context: ./frontend/AdoptAPet
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - adoptapetnet
    depends_on:
      - backend

networks:
  adoptapetnet:

volumes:
  postgres_data:
