name: Frontend test

on:
  push:
    branches: [ "fki-pipeline-setup" ]
  pull_request:
    branches: [ "fki-pipeline-setup" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: rescue-team-features

      - name: Build the project
        # env:
        #    POSTGRES_USER: ${{secrets.POSTGRES_USER}}
        #    POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        #    POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        run: |
          # export POSTGRES_USER=${{secrets.POSTGRES_USER}}
          # export POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          # export POSTGRES_DB=${{secrets.POSTGRES_DB}}
          docker compose up -d

      - name: Wait for build
        run: |
         retries=10
                     while [ $retries -gt 0 ]; do
                     if curl -s http://localhost:4200 > /dev/null; then
                     break
                     else
                     sleep 10
                     retries=$((retries - 1))
                     fi
                     done
          docker compose logs 
          curl -v http://localhost:4200

      - name: Checkout the test repository
        uses: actions/checkout@v4
        with:
          repository: FoldiKrizsanIldiko/adoptAPet
          token: ${{secrets.FKI_ADOPTAPET}}
          ref: fki-Frontend-tests

      - name: Run tests CI tests
        run: |
          cd FontendTests/adoptAPetFrontend
          mvn test -Dcucumber.filter.tags="@workflow"

      - name: Tear down services
        run: docker-compose down
   
