name: Backend test

on:
  push:
    branches: [ "fki-pipeline-setup" ]
    paths-ignore:
      - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:


          
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: rescue-team-features

      - name: Build the project
        run: |
          docker compose up -d

      - name: Wait for build
        run: |
         retries=10
                     while [ $retries -gt 0 ]; do
                     if curl -s http://localhost:4200 > /dev/null; then
                     break
                     else
                     sleep 10
                     retries=$((retries - 1))
                     fi
                     done

      - name: Checkout the test repository
        uses: actions/checkout@v4
        with:
          repository: FoldiKrizsanIldiko/adoptAPet
          token: ${{secrets.FKI_ADOPTAPET}}
          ref: fki-API-Postman-tests

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install newman with reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      #Create folder to export results
      - name: Create folder
        run: mkdir Testresults

      - name: List files in the directory
        run: ls -R 

      # Run collection
      - name: Run collection
        run: |
          newman run "Adopt_A_Pet_CI.postman_collection.json" -r htmlextra --reporter-htmlextra-export Testresults/result.html
      # Publish the report

      - name: Publish report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: Testresults
